-- Run in the Supabase SQL editor on a new project.
create extension if not exists pgcrypto;

create table public.admin_users (user_id uuid primary key references auth.users(id) on delete cascade, created_at timestamptz not null default now());
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists (select 1 from public.admin_users where user_id=auth.uid()) $$;
create table public.profiles (user_id uuid primary key references auth.users(id) on delete cascade, name text, gender text, dob date, city text, education text, career text, relationship_goal text, future_goal text, values text[] default '{}', lifestyle text[] default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.analyses (id uuid primary key default gen_random_uuid(), owner_user_id uuid references auth.users(id) on delete set null, session_id uuid, status text not null default 'complete', analysis_type text[] not null default '{}', free_or_paid text not null default 'free' check (free_or_paid in ('free','paid')), created_at timestamptz not null default now());
create table public.analysis_people (id uuid primary key default gen_random_uuid(), analysis_id uuid not null references public.analyses(id) on delete cascade, person_role text not null check (person_role in ('A','B')), name text not null, gender text, dob date, tob time, birth_place text, relationship_goal text, values text[] default '{}', lifestyle text[] default '{}', consent_confirmed boolean not null default false);
create table public.uploads (id uuid primary key default gen_random_uuid(), analysis_id uuid not null references public.analyses(id) on delete cascade, person_id uuid references public.analysis_people(id) on delete cascade, type text not null, storage_path text not null unique, mime_type text not null, size_bytes integer not null check(size_bytes > 0), created_at timestamptz not null default now());
create table public.compatibility_results (analysis_id uuid primary key references public.analyses(id) on delete cascade, overall_score integer check(overall_score between 0 and 100), values_score integer, relationship_score integer, lifestyle_score integer, career_score integer, age_score integer, location_score integer, education_score integer, explanation jsonb, created_at timestamptz not null default now());
create table public.readings (id uuid primary key default gen_random_uuid(), analysis_id uuid not null references public.analyses(id) on delete cascade, reading_type text not null check(reading_type in ('jataka','palm','numerology','relationship','future')), generated_text jsonb not null, model text, created_at timestamptz not null default now());
create table public.usage_limits (id uuid primary key default gen_random_uuid(), session_id uuid not null, user_id uuid references auth.users(id) on delete cascade, created_at timestamptz not null default now());
create table public.consents (id uuid primary key default gen_random_uuid(), analysis_id uuid not null references public.analyses(id) on delete cascade, user_id uuid references auth.users(id) on delete set null, consent_text_version text not null default '1.0', accepted_at timestamptz not null default now());
create table public.audit_logs (id uuid primary key default gen_random_uuid(), admin_user_id uuid references auth.users(id) on delete set null, action text not null, target_type text not null, target_id uuid, created_at timestamptz not null default now());
create index analyses_owner_idx on public.analyses(owner_user_id); create index analyses_session_idx on public.analyses(session_id); create index uploads_analysis_idx on public.uploads(analysis_id);

alter table public.admin_users enable row level security; alter table public.profiles enable row level security; alter table public.analyses enable row level security; alter table public.analysis_people enable row level security; alter table public.uploads enable row level security; alter table public.compatibility_results enable row level security; alter table public.readings enable row level security; alter table public.usage_limits enable row level security; alter table public.consents enable row level security; alter table public.audit_logs enable row level security;
create policy "profile owner" on public.profiles for all to authenticated using (user_id=auth.uid() or public.is_admin()) with check (user_id=auth.uid());
create policy "analysis owner" on public.analyses for select to authenticated using (owner_user_id=auth.uid() or public.is_admin());
create policy "people owner" on public.analysis_people for select to authenticated using (exists(select 1 from public.analyses a where a.id=analysis_id and (a.owner_user_id=auth.uid() or public.is_admin())));
create policy "uploads owner" on public.uploads for select to authenticated using (exists(select 1 from public.analyses a where a.id=analysis_id and (a.owner_user_id=auth.uid() or public.is_admin())));
create policy "results owner" on public.compatibility_results for select to authenticated using (exists(select 1 from public.analyses a where a.id=analysis_id and (a.owner_user_id=auth.uid() or public.is_admin())));
create policy "readings owner" on public.readings for select to authenticated using (exists(select 1 from public.analyses a where a.id=analysis_id and (a.owner_user_id=auth.uid() or public.is_admin())));
create policy "consents owner" on public.consents for select to authenticated using (user_id=auth.uid() or public.is_admin());
create policy "admin audit" on public.audit_logs for select to authenticated using (public.is_admin());
-- Keep user-uploads bucket private. Create it in Storage UI, then apply these policies.
create policy "storage upload own folder" on storage.objects for insert to authenticated with check (bucket_id='user-uploads' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "storage read owner or admin" on storage.objects for select to authenticated using (bucket_id='user-uploads' and ((storage.foldername(name))[1]=auth.uid()::text or public.is_admin()));
create policy "storage delete owner or admin" on storage.objects for delete to authenticated using (bucket_id='user-uploads' and ((storage.foldername(name))[1]=auth.uid()::text or public.is_admin()));
